[project]
name = "minecraft-control"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "mangum>=0.19.0",
]
[dependency-groups]
dev = [
    "boto3>=1.34",
    "fastapi[standard]>=0.115",
]

[tool.uv]
